spring.application.name=backend

# DB - MySQL (local default; override via env vars)
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/appbit}
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACION DE BASE DE DATOS
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-fragrant-glitter-at2cexff-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_WbQp2gUI1ZlD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIoN DEL AGENTE IA (BE3)
# ==========================================
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.openai.chat.options.temperature=0.2

# ==========================================
# HILOS VIRTUALES Y JPA / HIBERNATE
# ==========================================
spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

# spring.h2.console.enabled=true