INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (1, 'MID', 'São José', 'Centro', -27.413, -48.4753, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (2, 'JUNIOR', 'Biguaçu', 'Oeste', -27.4156, -48.5147, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (3, 'SENIOR', 'São José', 'Norte', -27.6408, -48.506, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (4, 'JUNIOR', 'Florianópolis', 'Sul', -27.4078, -48.4543, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (5, 'SENIOR', 'Biguaçu', 'Oeste', -27.5427, -48.4499, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (6, 'MID', 'Florianópolis', 'Leste', -27.4774, -48.5222, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (7, 'SENIOR', 'Palhoça', 'Centro', -27.4896, -48.5384, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (8, 'JUNIOR', 'Florianópolis', 'Oeste', -27.5305, -48.4912, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (9, 'SENIOR', 'Florianópolis', 'Oeste', -27.5631, -48.5649, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (10, 'SENIOR', 'Florianópolis', 'Oeste', -27.6208, -48.5684, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (11, 'SENIOR', 'Palhoça', 'Sul', -27.538, -48.4928, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (12, 'SENIOR', 'Palhoça', 'Centro', -27.6847, -48.5016, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (13, 'JUNIOR', 'Palhoça', 'Oeste', -27.6066, -48.4187, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (14, 'MID', 'Palhoça', 'Centro', -27.5412, -48.4073, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (15, 'JUNIOR', 'Biguaçu', 'Leste', -27.4476, -48.4657, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (16, 'JUNIOR', 'Palhoça', 'Sul', -27.6346, -48.4755, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (17, 'SENIOR', 'São José', 'Norte', -27.6605, -48.5389, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (18, 'JUNIOR', 'Palhoça', 'Centro', -27.6026, -48.4885, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (19, 'MID', 'Biguaçu', 'Norte', -27.5362, -48.4168, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (20, 'SENIOR', 'São José', 'Sul', -27.4692, -48.4111, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (21, 'SENIOR', 'São José', 'Centro', -27.4923, -48.507, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (22, 'JUNIOR', 'Florianópolis', 'Sul', -27.4666, -48.5603, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (23, 'JUNIOR', 'Biguaçu', 'Sul', -27.6445, -48.5586, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (24, 'MID', 'Florianópolis', 'Sul', -27.4046, -48.4917, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (25, 'MID', 'Biguaçu', 'Leste', -27.6146, -48.4712, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (26, 'SENIOR', 'São José', 'Norte', -27.6722, -48.558, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (27, 'JUNIOR', 'Palhoça', 'Leste', -27.5463, -48.5166, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (28, 'JUNIOR', 'Biguaçu', 'Norte', -27.5823, -48.5679, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (29, 'JUNIOR', 'São José', 'Norte', -27.6789, -48.5877, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (30, 'JUNIOR', 'Biguaçu', 'Sul', -27.5125, -48.5147, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (31, 'SENIOR', 'Biguaçu', 'Leste', -27.5024, -48.4106, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (32, 'MID', 'Palhoça', 'Leste', -27.4951, -48.4737, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (33, 'SENIOR', 'Biguaçu', 'Oeste', -27.4888, -48.5802, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (34, 'SENIOR', 'Palhoça', 'Centro', -27.6961, -48.5883, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (35, 'MID', 'Biguaçu', 'Norte', -27.6301, -48.4094, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (36, 'MID', 'Palhoça', 'Sul', -27.5345, -48.5924, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (37, 'MID', 'Biguaçu', 'Centro', -27.5608, -48.4625, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (38, 'SENIOR', 'Florianópolis', 'Norte', -27.639, -48.5852, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (39, 'SENIOR', 'Florianópolis', 'Sul', -27.6354, -48.5411, NULL);
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (40, 'SENIOR', 'Florianópolis', 'Leste', -27.4098, -48.4588, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (41, 'JUNIOR', 'Palhoça', 'Oeste', -27.5017, -48.5223, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (42, 'SENIOR', 'Palhoça', 'Leste', -27.5225, -48.5746, 'Black/Brown');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (43, 'SENIOR', 'Florianópolis', 'Leste', -27.5434, -48.5113, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (44, 'JUNIOR', 'São José', 'Centro', -27.4928, -48.5671, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (45, 'SENIOR', 'Biguaçu', 'Sul', -27.4616, -48.4771, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (46, 'MID', 'Florianópolis', 'Sul', -27.5574, -48.4938, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (47, 'MID', 'Palhoça', 'Oeste', -27.5134, -48.5365, 'Women in Tech');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (48, 'SENIOR', 'Biguaçu', 'Oeste', -27.4171, -48.4723, 'PCD');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (49, 'JUNIOR', 'São José', 'Oeste', -27.4526, -48.5268, 'LGBTQ+');
INSERT INTO candidate (id, experience_level, municipio, cluster, latitude, longitude, diversity_badge) VALUES (50, 'MID', 'Palhoça', 'Norte', -27.6125, -48.5796, 'Women in Tech');

INSERT INTO candidate_skills (candidate_id, skill) VALUES (1, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (1, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (1, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (2, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (2, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (2, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (2, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (3, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (3, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (4, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (4, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (4, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (4, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (5, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (5, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (5, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (5, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (5, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (6, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (6, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (6, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (6, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (6, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (7, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (7, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (8, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (8, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (8, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (8, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (9, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (9, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (9, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (10, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (10, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (10, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (10, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (11, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (11, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (11, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (11, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (12, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (12, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (12, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (13, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (13, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (13, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (13, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (14, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (14, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (15, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (15, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (15, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (16, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (16, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (16, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (16, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (17, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (17, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (17, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (18, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (18, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (18, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (18, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (19, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (19, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (19, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (19, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (20, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (20, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (20, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (21, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (21, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (21, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (21, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (21, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (22, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (22, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (22, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (23, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (23, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (23, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (23, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (24, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (24, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (24, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (24, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (25, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (25, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (26, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (26, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (26, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (26, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (27, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (27, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (28, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (28, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (28, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (28, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (28, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (29, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (29, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (29, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (30, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (30, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (30, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (30, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (31, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (31, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (31, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (31, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (32, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (32, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (33, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (33, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (33, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (34, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (34, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (34, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (34, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (34, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (35, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (35, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (35, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (35, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (36, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (36, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (36, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (36, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (37, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (37, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (38, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (38, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (39, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (39, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (40, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (40, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (40, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (40, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (41, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (41, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (42, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (42, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (42, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (43, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (43, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (44, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (44, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (44, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (44, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (44, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (45, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (45, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (45, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (45, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (45, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (46, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (46, 'Java');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (46, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (47, 'SQL');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (47, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (47, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (47, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (48, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (48, 'Docker');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (48, 'Kubernetes');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (49, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (49, 'AWS');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (49, 'React');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (50, 'Python');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (50, 'Spring Boot');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (50, 'Angular');
INSERT INTO candidate_skills (candidate_id, skill) VALUES (50, 'SQL');
